packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.7'
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
