import type * as PrismaClient from "@prisma/client";

export type LanguageRecord = PrismaClient.Language;
export type MarketRecord = PrismaClient.Market;
export type MarketLocaleRecord = PrismaClient.MarketLocale;
export type UserRecord = PrismaClient.User;
export type RoleRecord = PrismaClient.Role;
export type UserRoleRecord = PrismaClient.UserRole;
export type AddressRecord = PrismaClient.Address;
export type SessionRecord = PrismaClient.Session;
export type SubscriptionRecord = PrismaClient.Subscription;
export type PrivacyRequestRecord = PrismaClient.PrivacyRequest;
export type NotificationDeliveryRecord = PrismaClient.NotificationDelivery;
export type PermissionRecord = PrismaClient.Permission;
export type RolePermissionRecord = PrismaClient.RolePermission;
export type UserPermissionRecord = PrismaClient.UserPermission;
export type DealerApplicationRecord = PrismaClient.DealerApplication;
export type DealerCompanyRecord = PrismaClient.DealerCompany;
export type DealerMemberRecord = PrismaClient.DealerMember;
export type DealerAddressRecord = PrismaClient.DealerAddress;
export * from "./client.js";
